print("creat a repository")
print("add a file")
print("do the changes")
print("commit the changes")
print("push the changes to the remote repository")
print("create a pull request")
print("merge the pull request")
print("test reset")

print(1)
