print("creat a repository")
print("add a file")
print("do the changes")
print("commit the changes")
print("push the changes to the remote repository")
print("create a pull request")
print("merge the pull request")
print("test reset")

print(1)
print(2)
print(3)
print(4)
print(5)
print(6)
print(7)
print(8)
print(9)

print("new branch")
print("add a file")
print("do the changes")
print("commit the changes")
print(3)
print("2024-10-9-001")
print("dev branch")
print("fix bug")
